language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=allegro
    - LISP=abcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/prove ~/lisp/prove

script:
  - cl -l prove
       -e '(or (prove:run :quri-test)
               (uiop:quit -1))'
